### ISSUE TITLE
100% CPU load after writing to named pipe in XDG_RUNTIME_DIR

### ISSUE THREAD

**Issue by ForzCross** [MadcowOG/dwl-bar#11]
During my experiments with statusline generation i noticed full cpu core usage after closing my script (and therefore closing fifo to dwl-bar-0).
I figured out that the issue comes from `void fifo_in(...)` not handling `POLLHUP` properly, what caused high cpu usage trying to read from closed fifo.

**Comment by ForzCross** [comment]
I came up with the following solution:
```cpp
void fifo_in(int fd, short mask, void *data) {                                                                                                                                                                                                                                    
    if (mask & POLLHUP) {
        events_remove(events, fd);
        unlink(fifo_path);
        fifo_setup();
        events_add(events, fifo_fd, POLLIN, NULL, fifo_in);
        return;
    } 
...
}
```

I'm not sure if it's a good idea to reopen fifo on POLLERR, so just left it as is.

BTW i would remove bar status reset. Less code and follows the dwm bar behaviour.

**Comment by 0mark** [comment]
I changed O_RDONLY to O_RDWR in _fifo_setup_, so we don't get POLLHUP in the first place. Found that on [Stackoverflow](https://stackoverflow.com/questions/22021253/poll-on-named-pipe-returns-with-pollhup-constantly-and-immediately) and it seemed reasonable. Works fine for me so far.

**Comment by ForzCross** [comment]
Solution with `O_RDWR` works great! I'll update my PR.

**Comment by MadcowOG** [comment]
I apologize for this problem, I didn't know about this problem when I wrote this version of dwl-bar. Thank you and @0mark  for fixing this.

**Comment by MadcowOG** [comment]
I have merged the pr, thanks for the help!
