### ISSUE TITLE
wl_registry@2: error 0: invalid version for global zwlr_layer_shell_v1 (18): have 3, wanted 4

### ISSUE THREAD

**Issue by OH016** [MadcowOG/dwl-bar#13]

**Comment by Charadon** [comment]
I'm getting this error too, how'd you fix it?

**Comment by marendowski** [comment]
Me too.

**Comment by Charadon** [comment]
> Me too.

I actually figured it out a few days ago. Basically find the line in dwl.c:
`layer_shell = wlr_layer_shell_v1_create(dpy, 3);`

and change the 3 to a 4.

**Comment by marendowski** [comment]
> > Me too.
> 
> I actually figured it out a few days ago. Basically find the line in dwl.c: `layer_shell = wlr_layer_shell_v1_create(dpy, 3);`
> 
> and change the 3 to a 4.

Wow, thanks! Is it something wrong with dwl, so we need to open a new issue?

**Comment by Charadon** [comment]
> > > Me too.
> > 
> > 
> > I actually figured it out a few days ago. Basically find the line in dwl.c: `layer_shell = wlr_layer_shell_v1_create(dpy, 3);`
> > and change the 3 to a 4.
> 
> Wow, thanks! Is it something wrong with dwl, so we need to open a new issue?

Well, they bumped it down to 3 recently from what I could tell, so i'm sure they had their reasons. Since I don't know anything about Wayland, I have no idea what the consequences of this fix could be, but it works fine for me so far.
