### ISSUE TITLE
dwl-bar is not showing

### ISSUE THREAD

**Issue by 0x72756279** [MadcowOG/dwl-bar#3]
I'm running the latest dwl.

When compiling dwl-bar and running it the process is up but no bar is shown...
Maybe I'm running it the wrong way?

I'm using the IPC patch BTW....

**Comment by MadcowOG** [comment]
Have you applied the [ipc](https://github.com/djpohly/dwl/wiki/ipc) patch for dwl and if so are you on the latest version?

**Comment by 0x72756279** [comment]
> Have you applied the [ipc](https://github.com/djpohly/dwl/wiki/ipc) patch for dwl and if so are you on the latest version?

Yes, I applied v2 of the IPC.
But even without it - shouldn't the bar be drawn at least?

Any information I can provide to help discover the issue?

**Comment by MadcowOG** [comment]
> But even without it - shouldn't the bar be drawn at least?

Without the ipc patch on both ends the bar won't get past setup, because the actual communication is done via wayland globals (these are checked before we even create the shared memory for the bar to use).

> Any information I can provide to help discover the issue?

I'm guessing the bar is just crashing right off the bat? Is there an error message?

**Comment by 0x72756279** [comment]
> Without the ipc patch on both ends the bar won't get past setup, because the actual communication is done via wayland globals (these are checked before we even create the shared memory for the bar to use).

OK, if I understand correctly - if `dwl` has the IPC patch and `dwl-bar` does not - there is still an attempt to create the IPC communication? 

> I'm guessing the bar is just crashing right off the bat? Is there an error message?

Nop:
- If I'm using the main branch without the IPC patch - the bar process hangs.
- For the IPC branch I get the following on build:

```c
gcc src/xdg-shell-protocol.o src/xdg-output-unstable-v1-protocol.o src/wlr-layer-shell-unstable-v1-protocol.o src/dwl-bar-ipc-unstable-v1-protocol.o src/main.c src/bar.c src/shm.c src/config.h `pkg-config --libs wayland-client wayland-cursor pangocairo`  `pkg-config --cflags wayland-client wayland-cursor pangocairo` -O1 -o dwl-bar
In file included from src/main.c:24:
src/config.h:37:20: error: conflicting types for ‘tags’; have ‘const char *[]’
   37 | static const char* tags[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9" };
      |                    ^~~~
In file included from src/bar.h:7,
                 from src/main.c:22:
src/common.h:53:17: note: previous declaration of ‘tags’ with type ‘wl_array’
   53 | extern wl_array tags, layouts;
      |                 ^~~~
In file included from src/bar.c:9:
src/config.h:37:20: error: conflicting types for ‘tags’; have ‘const char *[]’
   37 | static const char* tags[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9" };
      |                    ^~~~
In file included from src/config.h:3:
src/common.h:53:17: note: previous declaration of ‘tags’ with type ‘wl_array’
   53 | extern wl_array tags, layouts;
      |                 ^~~~
src/config.h:37:20: error: conflicting types for ‘tags’; have ‘const char *[]’
   37 | static const char* tags[] = { "1", "2", "3", "4", "5", "6", "7", "8", "9" };
      |                    ^~~~
In file included from src/config.h:3:
src/common.h:53:17: note: previous declaration of ‘tags’ with type ‘wl_array’
   53 | extern wl_array tags, layouts;
      |                 ^~~~
make: *** [Makefile:30: dwl-bar] Error 1
```

Thanks for the hard work.

**Comment by 0x72756279** [comment]
Sorry, I was able to build the IPC branch right now and everything looks OK.

The problem was a remaining `config.h` from the main branch with a conflict type for the tags array.

You can close this issue.
Thanks.

**Comment by MadcowOG** [comment]
It's all good, that config.h is left over from the dwl Makefile (I copy pasted most of it), the clean target doesn't remove config.h (dwm's makefile does). So I plan on fixing that.

Just to be extra clear, the ipc patch for dwl doesn't break the regular stdout > stdin communication method through -s usage of bars, it only adds the ability for clients to ask for the ipc globals via wayland and communicate there. But on dwl-bar's side we no longer try to look at the stdin for communication from dwl that way. We only look through the wayland globals we ask for. I hope that makes sense.
