### ISSUE TITLE
IPC Patch Failed 1 out of 13 hunks

### ISSUE THREAD

**Issue by rickswe** [MadcowOG/dwl-bar#4]
Hello, I'm trying to get waybar working with dwl tags. Not sure if this patch
needs to be updated. I used the [2023-04-02 patch](https://github.com/djpohly/dwl/compare/main...madcowog:ipcv3.patch).

Thanks

**Comment by MadcowOG** [comment]
Yes, sorry. I reworked everything so not all patches will work. As of now, ipc, and hide vacant tags should work. I am working on systray right now.
Please let me know if everything works.

**Comment by MadcowOG** [comment]
I assuming that this issue is solved, due to the lack of response. If the problem continues please open another!
