### ISSUE TITLE
dwl without ipc  & dwl-bar without ipc

### ISSUE THREAD

**Issue by kristoferus75** [MadcowOG/dwl-bar#8]
Hi
 
without ipc patch :

i don't see on bar on which tag im currently 

somebar also not visible on bar

```
~/annex/dotfiles/dwl-bar/dwl-bar &
sleep 0.1
~/annex/dotfiles/someblocks/someblocks -s /run/user/1000/dwl-bar-0

```
 
with ipc -> all work but -> very often complete freezes of the pc

coredumpctl -> dwl-bar

**Comment by MadcowOG** [comment]
When not patched with dwl-ipc, dwl-bar requires stdin input from dwl by launching it like so:
`dwl -s 'dwl-bar'`
But then when we are patched with the ipc / dwl doesn't have any applications to pass information into, dwl will block.
This is likely the freezing that you are seeing.
avoid this like so:
`dwl -s 'dwl-bar <&-'`
You should see the dwl README for more information on this.

**Comment by kristoferus75** [comment]
Hi ! 

Thanks !

i thing i have already configured it but im not sure if this way is ok because with this i see freezes:

`exec dbus-run-session ~/dotfiles/dwl/dwl -s '~/autostart_dwl.sh' 2>&1 | tee "$LOGDIR"/dwl.log`

autostart_dwl.sh 

```
~/dotfiles/dwl-bar/dwl-bar &<- &
sleep 0.1
~/dotfiles/someblocks/someblocks -s /run/user/1000/dwl-bar-0
```


ok is this my mistake? 

`&<-`   <>  `<&-`

**Comment by kristoferus75** [comment]
Sorry it seems that a patch cause this issue but not the ipc patch or the dwl-bar !

i use this patches with dwl:

`pertag.patch 
attachbottom.patch  
switchotag.patch 
autostart.patch 
ipc_dwl_bar.patch  
master-right.patch 
movestack.patch 
menu.patch 
simplegaps.patch  `

Sorry !!!

**Comment by kristoferus75** [comment]
after adpat my autostart script -> no freezes :

```
exec ~/annex/dotfiles/dwl-bar/dwl-bar <&- &
sleep 0.1
exec ~/annex/dotfiles/someblocks/someblocks -s /run/user/1000/dwl-bar-0 <&-
```
